### ISSUE TITLE
Error: ApiException

### ISSUE THREAD

**Issue by setegonz** [olafwrieden/batch-transcription-python-azure-databricks#3]
This is what I have done so far to complete the missing variables:

RECORDINGS_BLOB_URI: I went to "batchtranscriptionstore/recordings" right clicked on the only file I have (just to test) and clicked on "generate sas". Then I clicked on "generate SAS token and URL" and pasted the url in this variable..

RECORDINGS_CONTAINER_URI: I went to "batchtranscriptionstore/recordings" "generate sas". Then I clicked on "generate SAS token and URL" and pasted the url in this variable.

destinationContainerUrl: I went to "batchtranscriptionstore/transcriptions" "generate sas". Then I clicked on "generate SAS token and URL" and pasted the url in this variable.

Then I'm having the following error in the last cell:

```
ApiException                              Traceback (most recent call last)
<command-51846924380767> in <module>
     79 
     80 if __name__ == "__main__":
---> 81     transcribe()

<command-51846924380767> in transcribe()
     39 
     40     created_transcription, status, headers = api.create_transcription_with_http_info(
---> 41         transcription=transcription_definition)
     42 
     43     # get the transcription Id from the location URI

/local_disk0/.ephemeral_nfs/envs/pythonEnv-84f1a874-c1e6-4726-b9ce-4f911ac9a0dd/src/swagger-client/python-client/swagger_client/api/default_api.py in create_transcription_with_http_info(self, **kwargs)
    800             _preload_content=params.get('_preload_content', True),
    801             _request_timeout=params.get('_request_timeout'),
--> 802             collection_formats=collection_formats)
    803 
    804     def delete_base_model_log(self, locale, log_id, **kwargs):  # noqa: E501

```

Am I doing something wrong?

**Comment by olafwrieden** [comment]
Hmm strange.. I can't replicate this error. From what I can tell, you have copied the correct `Blob SAS URL`. Perhaps when generating the SAS token, select `HTTPS and HTTP` under 'Allowed Protocols' and check if perhaps this is an HTTPS issue.

For the source container (RECORDINGS_CONTAINER_URI) variable, please try selecting both `read` and `list` permissions when generating the SAS token to allow it to enumerate the container.

The destination container (destinationContainerUrl) variable should be a SAS token with `Write` access to the blob storage, to allow it to write the output JSON back to the store. If you just want to log the transcription file to the console rather than saving it, you can comment out this variable in the `properties` object.

Did you run the cell containing the variables before running the cell that contains the `transcribe()` method? Otherwise python wouldn't have registered a change to the variable and will refer to whatever value (if any) it had in memory.

Let me know if any of this was helpful as I was unable to reproduce.

**Comment by setegonz** [comment]
Closing this issue based on the information available in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/888#issuecomment-740546995.  I was using a free subscription (level F0). The batch transcription service can only be used with a paid standard subscription (level S0).
